export const HOME_HREF = '/'
export const PROFILE_HREF = '/profile'
export const PRIVACY_HREF = '/privacy'
export const LEGAL_HREF = '/legal'
export const COOKIES_POLICY_HREF = '/cookies-policy'
export const CDTI_HREF = '/grants/cdti'
export const INNOVATION_SME_HREF = '/grants/innovative-sme'
export const NEWS_ROOM_HREF = '/news'
