export const HOME_HREF = '/'
export const PROFILE_HREF = '/profile'
export const PRIVACY_LEGAL = '/privacy-legal'
export const CDTI_HREF = '/grants/cdti'
export const INNOVATION_SME_HREF = '/grants/innovative-sme'
