import GhostTag from './GhostTag'

/* eslint-disable camelcase */
export default interface GhostPost {
  slug: string,
  id: string,
  uuid: string,
  title: string,
  html: string,
  comment_id: string,
  feature_image: string | null,
  featured: boolean,
  visibility: string,
  created_at: string,
  updated_at: string,
  published_at: string,
  custom_excerpt: string | null,
  codeinjection_head: string | null,
  codeinjection_foot: string | null,
  custom_template: string | null,
  canonical_url: string | null,
  send_email_when_published: boolean,
  url: string,
  excerpt: string,
  reading_time: number,
  access?: boolean,
  og_image: string | null,
  og_title: string | null,
  og_description: string | null,
  twitter_image: string | null,
  twitter_title: string | null,
  twitter_description: string | null,
  meta_title: string | null,
  meta_description: string | null,
  email_subject: string | null
  author?: GhostAuthor[],
  tags?: GhostTag[],
  primary_author?: GhostAuthor,
  primary_tag?: GhostTag
}
